apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: etcd-operator
  namespace: openshift-etcd-operator
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
spec:
  endpoints:
  - interval: 30s
    port: https
    scheme: https
    tlsConfig:
      serverName: metrics.openshift-etcd-operator.svc
  jobLabel: app
  scrapeClass: tls-client-certificate-auth
  selector:
    matchLabels:
      app: etcd-operator
  serviceDiscoveryRole: EndpointSlice
