apiVersion: v1
kind: ConfigMap
metadata:
  namespace: openshift-etcd-operator
  name: etcd-operator-config
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
data:
  config.yaml: |
    apiVersion: operator.openshift.io/v1alpha1
    kind: GenericOperatorConfig
---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    release.openshift.io/create-only: "true"
  name: etcd-ca-bundle
  namespace: openshift-etcd-operator
---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    release.openshift.io/create-only: "true"
    service.beta.openshift.io/inject-cabundle: "true"
  name: etcd-service-ca-bundle
  namespace: openshift-etcd-operator
