apiVersion: v1
kind: Service
metadata:
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    service.alpha.openshift.io/serving-cert-secret-name: etcd-operator-serving-cert
  labels:
    app: etcd-operator
  name: metrics
  namespace: openshift-etcd-operator
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: etcd-operator
  sessionAffinity: None
  type: ClusterIP
