---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cluster-etcd-operator-staticpod
rules:
- apiGroups: ["machineconfiguration.openshift.io"]
  resources: ["machineconfigpools", "machineconfigs"]
  verbs: ["get", "list"]
- apiGroups: ["operator.openshift.io"]
  resources: ["etcds"]
  verbs: ["get", "watch", "list"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cluster-etcd-operator-staticpod
  namespace: openshift-etcd
subjects:
- kind: ServiceAccount
  name: default
  namespace: openshift-etcd
roleRef:
  kind: ClusterRole
  namespace: openshift-etcd
  name: cluster-etcd-operator-staticpod
  apiVersion: rbac.authorization.k8s.io/v1beta1
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: openshift-etcd
  name: cluster-etcd-operator-staticpod
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cluster-etcd-operator-staticpod
  namespace: openshift-etcd
subjects:
- kind: ServiceAccount
  name: default
  namespace: openshift-etcd
roleRef:
  kind: Role
  namespace: openshift-etcd
  name: cluster-etcd-operator-staticpod
  apiVersion: rbac.authorization.k8s.io/v1beta1
