apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:openshift:operator:etcd-operator
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
roleRef:
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  namespace: openshift-etcd-operator
  name: etcd-operator
