apiVersion: v1
kind: Service
metadata:
  name: host-etcd-2
  namespace: openshift-etcd
  labels:
    # this label is used to indicate that it should be scraped by prometheus
    k8s-app: etcd
  finalizers:
  - openshift.io/etcd-operator
spec:
  clusterIP: None
  ports:
  - name: etcd
    port: 2379
    protocol: TCP
