apiVersion: v1
kind: Secret
type: SecretTypeTLS
metadata:
  # this etcd client key/crt is a placeholder and is mounted by the operator
  # it will later be populated by the resourcesynccontroller
  name: etcd-client
  namespace: openshift-etcd-operator
data:
  tls.crt: stub 
  tls.key: stub

